spring:
  datasource:
    url: jdbc:mysql://j9a102.p.ssafy.io/ssafety?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: a102
    password: ssafy102
#    url: jdbc:mysql://localhost:3306/ssafety
#    username: a102
#    password: a102
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
server:
  port: 8080
cloud:
  aws:
    credentials:
      accessKey: AKIAS42RRQAHDNJMABZF
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

kakao:
  api:
    key: 4dcde7448c280266730f45df159cd184

logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: DEBUG

naver-cloud-sms:
  accesskey: pefU3d4Q23IViWLRqACL
  secretkey: EAjKgQXNMKtmnNQiJYFWRXxxpEshX7MzcNZMOmBA
  serviceId: ncp:sms:kr:310688378438:subpjt
  phone: 01049489610

cctv:
  apiKey=0db19b82b4d84ef3846c147df0b0028d
